version: '3.8'

services:
  lms-db:
    image: postgres:alpine
    container_name: lms_postgres_db
    environment:
      POSTGRES_USER: corn
      POSTGRES_PASSWORD: corn244466666
      POSTGRES_DB: LMSSystem
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lms-network

  lms-api:
    image: lms-api
    build:
      context: .
      dockerfile: PRN232.LMSSystem.API/Dockerfile
    container_name: lms_web_api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Host=lms-db;Port=5432;Database=LMSSystem;Username=corn;Password=corn244466666
    depends_on:
      - lms-db
    networks:
      - lms-network

volumes:
  pgdata:

networks:
  lms-network:
    driver: bridge
